import type { Metadata } from "next";
import "./globals.css";
import PageLoader from "@/components/PageLoader";
import { GoogleAnalytics } from "@next/third-parties/google"; 
// import MetaPixel from "../components/MetaPixel";

// 3. SEO e Metadados profissionais de forma nativa (Substituindo o "Generated by create next app")
export const metadata: Metadata = {
  title: "Clínica Divertin | Fonoaudiologia Infantil",
  description: "Pacotes e condições especiais para acompanhamento terapêutico infantil com horários fixos.",
  openGraph: {
    title: "Clínica Divertin | Fonoaudiologia Infantil",
    description: "Acompanhamento terapêutico lúdico e especializado para crianças.",
    images: ["/logo-compartilhamento.png"], // Imagem que aparece ao mandar o link no WhatsApp
  },
};

// Mantive exatamente a tipagem original do seu projeto andando
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR">
      {/* 
        REMOVIDO: A tag <head> manual foi removida. 
        O Next.js gerencia as fontes locais/externas direto no 'globals.css' ou via 'next/font'.
      */}
      <body className="min-h-full flex flex-col">
        <PageLoader src="/loading.gif" width={180} />
        {children}

        {/* 4. Scripts inseridos de forma otimizada antes do fechamento do body */}
        <GoogleAnalytics gaId="G-14VEB6PD4R" /> {/* Troque pelo seu ID real do Google */}
        {/* <MetaPixel /> */}
      </body>
    </html>
  );
}
